version: '3.8'

services:
  server:
    build:
      context: ./act-server
      dockerfile: Dockerfile
    volumes:
      - ./act-server/:/act-server/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./act-server/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
      image: postgres:13-alpine
      volumes:
          - postgres_data:/var/lib/postgresql/data/
      env_file:
         - ./act-server/.env
      ports:
          - 5432:5432
volumes:
        postgres_data:
